CREATE DATABASE OOP2_PROJECT_MOBILE_SHOP;

CREATE TABLE OWNER(
ID INT PRIMARY KEY,
NAME VARCHAR(40),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(30),
);

SELECT * FROM OWNER;

INSERT INTO OWNER VALUES(111,'SAMIO HASAN','samiohasan6@gmail.com','samio123');

CREATE TABLE CUSTOMER(
NAME VARCHAR(30),
AGE INT,
GENDER VARCHAR(25),
EMAIL VARCHAR(50) PRIMARY KEY,
PASSWORD VARCHAR(30),
);

CREATE TABLE VIVO(
PHONE_ID VARCHAR(30) PRIMARY KEY,
PHONE_MODEL VARCHAR(50),
PHONE_PRICE VARCHAR(15),
PHONE_DISCOUNT VARCHAR(20),
TOTAL_PRICE INT,
PHONE_PICTURE IMAGE

);



select * from VIVO;

delete from OPPO where PHONE_ID = '705';

drop table IPHONE;

SELECT * FROM CUSTOMER;


CREATE TABLE CRAFT
(PHONE_MODEL VARCHAR(50),
PHONE_ID VARCHAR(20) PRIMARY KEY,
PHONE_PRICE VARCHAR(20),
PHONE_PURCHASE_DATE VARCHAR(60)
);

SELECT * FROM CRAFT;

ALTER TABLE CRAFT ADD PAYMENT_STATUS VARCHAR(40);

INSERT INTO CUSTOMER VALUES('TAWKIR TAHA',22,'MALE','tawkirtaha45@gmail.com','taha112255');

CREATE TABLE EMPLOYEE(
EMPLOYEE_NAME VARCHAR(60),
EMPLOYEE_ID VARCHAR(20),
EMPLOYEE_POST VARCHAR(50),
EMPLOYEE_SALARY VARCHAR(20),
PHOTO IMAGE
);
drop table EMPLOYEE;
SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE ADD PHOTO VARCHAR(200);

select * from SVMSUNG;
ALTER TABLE SVMSUNG ADD AVILABLE_PRODUCT VARCHAR(40);
UPDATE SVMSUNG SET AVILABLE_PRODUCT = '10' WHERE PHONE_ID>'200';

ALTER TABLE SVMSUNG DROP COLUMN AVILABLE_PRODUCT;

